#!/bin/sh

if hash stylish-commit 2>/dev/null; then
  stylish-commit
else
  # Attempt to run locally
  if node -e "require('stylish-commit')" 2>/dev/null; then
    node -e "require('stylish-commit').run()"
  else
    echo "!! stylish-commit not found."
    echo "!! You should add it as a package dependency or run `npm install -g stylish-commit`"
    echo "!! or you can get rid of this message by deleting .git/hooks/pre-commit"
  fi
fi
